language: generic

sudo: false

before_install:
  - unset PYENV_ROOT
  - rm -rf ~/.pyenv
  - curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
  - export PATH="$HOME/.pyenv/bin:$PATH"

install:
  - virtualenv venv
  - source venv/bin/activate
  - pip install tox-travis tox-pyenv

script:
  - tox

after_script:
  - tox -e coverage
